# Generated by Django 3.2.6 on 2021-11-11 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='name', max_length=50, verbose_name='name')),
                ('titulo_h1', models.CharField(max_length=50, verbose_name='titulo')),
                ('titulo_h2', models.CharField(max_length=50, verbose_name='slogan')),
                ('imagebg', models.ImageField(upload_to='background', verbose_name='imagenbg')),
                ('imagemain', models.ImageField(upload_to='imagemain', verbose_name='imagenmain')),
                ('display', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, verbose_name='titulo')),
                ('resumen', models.CharField(blank=True, default='', max_length=250, verbose_name='resumen')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='clientes', verbose_name='imagen')),
                ('display', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, verbose_name='order')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.TextField(max_length=350, verbose_name='titulo')),
                ('respuesta', models.TextField(max_length=1000, verbose_name='resumen')),
            ],
            options={
                'verbose_name': 'Faq',
                'verbose_name_plural': 'Faqs',
            },
        ),
    ]
