# Generated by Django 3.2.6 on 2021-11-12 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_added',
            field=models.DateField(auto_now_add=True),
        ),
    ]
