# Generated by Django 3.2.6 on 2021-11-17 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_post_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['order', '-date_added'], 'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
    ]
