# Generated by Django 3.2.6 on 2021-11-17 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_post_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='metaDescription',
            field=models.TextField(blank=True, max_length=160),
        ),
    ]
